apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: farfetch-reader-pods
  namespace: lesson15
subjects:
- kind: User
  name: farfetch
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io