apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: lesson14
  labels:
    app: goweb
spec:
  containers:
    - name: web
      image: cr00z/lesson1:v0.2 ## укажите здесь свой образ из предыдущих уроков в формате 
                                ## image: <имя_пользователя>/<репозиторий>/<тег>
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP